# Generated by Django 5.1.7 on 2025-04-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='services', to='main.user'),
        ),
    ]
