version: '3.8'

services:
  db:
    container_name: Water-meters
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: norilsk1
      POSTGRES_DB: Water-meters
    ports:
      - "5432:5432"

  minio:
    container_name: Water-meters-MINIOcontainer
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: norilsk1
    ports:
      - "9000:9000" # Для API
      - "9001:9001"  
    volumes:
      - minio_data:/data  # Данные MinIO будут храниться в volume
    command: server /data --console-address ":9001"

volumes:
  minio_data:
