# Generated by Django 5.1.7 on 2025-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservice',
            name='gvs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='hvs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
