# Generated by Django 5.1.7 on 2025-05-19 17:12

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_application_form_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(default=1, storage=django_minio_backend.models.MinioBackend(bucket_name='images'), upload_to=''),
            preserve_default=False,
        ),
    ]
