# Generated by Django 5.1.7 on 2025-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
        migrations.AddField(
            model_name='service',
            name='owners',
            field=models.ManyToManyField(related_name='services', to='main.user'),
        ),
    ]
