# Generated by Django 5.1.7 on 2025-05-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_service_owners_remove_user_address_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
