# Generated by Django 5.1.7 on 2025-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gvs',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hvs',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
