# Generated by Django 5.1.7 on 2025-05-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_applicationservice_gvs_applicationservice_hvs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='form_date',
        ),
    ]
