# Generated by Django 5.1.7 on 2025-04-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_name_remove_user_role_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='apartment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='house',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
